env:
  cash_in_hand: 10000000 # 학습 시작 시 보유 현금
  max_stock: 5000 # 최대 매수, 매도 가능 주식 수
  trading_charge: 0.00015 # 거래 수수료
  trading_tax: 0.002 # 거래 세금

A3CAgent:
  Learning Rate: 0.001 # 학습률

model:
  name: EnhancedActorCritic # ActorCritic, EnhancedActorCritic
  parameters:
    hidden_layer: 2048 # 은닉층의 뉴런 개수(단층 신경망)
    hidden1_size: 1024 # 첫 번째 은닉층 뉴런 개수
    hidden2_size: 512 # 두 번째 은닉층 뉴런 개수
    dropout_rate: 0.2 # 드롭아웃 비율

training:
  n_processes: 8
  n_episodes: 128
  batch_size: 16

seeds:
  random: 9822234
  numpy: 6482355
  torch: 9120972

Logger:
  directory: D:\\ICTRLT\\utils\\Log