env:
  cash_in_hand: 10000000 # 학습 시작 시 보유 현금
  max_stock: 200 # 최대 매수, 매도 가능 주식 수
  trading_charge: 0.00015 # 거래 수수료
  trading_tax: 0.002 # 거래 세금

A3CAgent:
  Learning Rate: 0.001 # 학습률

ActorCritic:
  hidden_layer:
    size: 512  # 은닉층의 뉴런 개수

training:
  n_processes: 6
  n_episodes: 9096
  batch_size: 32

seeds:
  random: 347602
  numpy: 977378
  torch: 814199

Logger:
  directory: D:\\ICTRLT\\utils\\Log